version: '3'
services:
  weblate:
    image: weblate/weblate
    volumes:
      - weblate-data:/app/data
    restart: always
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - database
      - cache

  database:
    image: postgres:13-alpine
    volumes:
      - postgres13-data:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: always

volumes:
  weblate-data: {}
  postgres13-data: {}
  redis-data: {}
